name: Daily Real Estate Data Collection

on:
  schedule:
    - cron: '0 1 * * *'  # 매일 01:00 UTC에 실행
  workflow_dispatch:
    inputs:
      lawd_cd:
        description: '법정동 코드 (예: 11710-송파구, 11680-강남구, 11650-서초구)'
        required: true
        default: '11710'
        type: string
      months:
        description: '조회할 개월 수 (1~12)'
        required: true
        default: '2'
        type: string

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check environment variables
      run: |
        if [ -z "$MONGO_URL" ] || [ -z "$SERVICE_KEY" ]; then
          echo "Error: MONGO_URL or SERVICE_KEY is not set"
          exit 1
        fi
        
    - name: Run RealEstateDB
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
      run: |
        if [ "${{ github.event_name }}" = "schedule" ]; then
          echo "Running scheduled job..."
          python RealEstateDB.py --lawd_cd 11680 --months 2  # 강남구
          python RealEstateDB.py --lawd_cd 11710 --months 2  # 송파구
        else
          echo "Running manual job..."
          python RealEstateDB.py --lawd_cd ${{ github.event.inputs.lawd_cd }} --months ${{ github.event.inputs.months }} 