name: MongoDB Atlas 접근 테스트

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Runner IP Address
        id: get-ip
        run: echo "ip=$(curl -s https://checkip.amazonaws.com)" >> $GITHUB_OUTPUT

      - name: Add IP to MongoDB Atlas Whitelist
        id: allow-ip
        run: |
          curl -X POST \
            -u "${{ secrets.ATLAS_PUBLIC_KEY }}:${{ secrets.ATLAS_PRIVATE_KEY }}" \
            -H "Content-Type: application/json" \
            -d "[{\"ipAddress\":\"${{ steps.get-ip.outputs.ip }}/32\",\"comment\":\"GitHub Actions Runner\"}]" \
            "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.ATLAS_PROJECT_ID }}/accessList"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run tests
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_TEST: ${{ secrets.TELEGRAM_CHAT_ID_TEST }}
          TELEGRAM_CHAT_ID_JH: ${{ secrets.TELEGRAM_CHAT_ID_JH }}
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: |
          python db_test.py

      - name: Remove IP from MongoDB Atlas Whitelist
        if: always() && steps.allow-ip.outcome == 'success'
        run: |
          # IP 주소 목록을 가져와서 추가했던 IP 주소의 ID를 찾아 삭제
          ACCESS_LIST=$(curl -s -u "${{ secrets.ATLAS_PUBLIC_KEY }}:${{ secrets.ATLAS_PRIVATE_KEY }}" "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.ATLAS_PROJECT_ID }}/accessList")
          ENTRY_ID=$(echo "$ACCESS_LIST" | jq -r ".results[] | select(.ipAddress == \"${{ steps.get-ip.outputs.ip }}/32\") | .id")

          if [ ! -z "$ENTRY_ID" ]; then
            curl -X DELETE \
              -u "${{ secrets.ATLAS_PUBLIC_KEY }}:${{ secrets.ATLAS_PRIVATE_KEY }}" \
              "https://cloud.mongodb.com/api/atlas/v1.0/groups/${{ secrets.ATLAS_PROJECT_ID }}/accessList/$ENTRY_ID"
            echo "Removed IP ${{ steps.get-ip.outputs.ip }} from Atlas whitelist."
          else
            echo "IP ${{ steps.get-ip.outputs.ip }} not found in Atlas whitelist."
          fi
